inherit_from:
  - https://raw.githubusercontent.com/rails/rails/v6.0.0.rc1/.rubocop.yml

AllCops:
  Exclude:
    - Gemfile
    - bin/*
    - spec/dummy/**/*
    - spec/rails_helper.rb

LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal
