sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
branches:
  only:
    - master
env:
  - RAILS_ENV=test
before_script:
  - (cd spec/dummy && bin/rails db:setup)
after_script:
  - '[ ${TRAVIS_EVENT_TYPE} != "pull_request" ] && [ ${TRAVIS_BRANCH} = "master" ] && bundle exec codeclimate-test-reporter'
