sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
matrix:
  exclude:
    - rvm: 2.5.5
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails_5_0.gemfile
branches:
  only:
    - master
env:
  - RAILS_ENV=test
before_script:
  - (cd spec/dummy && bin/rails db:setup)
after_script:
  - '[ ${TRAVIS_EVENT_TYPE} != "pull_request" ] && [ ${TRAVIS_BRANCH} = "master" ] && bundle exec codeclimate-test-reporter'
